### PR TITLE
Add README instructions

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
@kewp When creating these instructions, I noticed that source code doesn't have Okta integration. Do you have the code for that? If so, can you please update the repo?

**Comment by kewp** [comment]
Right, I forgot to do that. I have updated the code on my repo at https://github.com/kewp. I tried to make a pull request but struggled. I think it’s becauae the okta one was forked from mine

**Comment by mraible** [comment]
If you updated yours, I can merge from upstream. Thanks!

**Comment by kewp** [comment]
Ok. Merge from master. The app-store branch is what the new article should end with

**Pull request merged**
